version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb

  nodeapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql